// ============================================================
// GRILOVAČKA U ÓÓČEK – Herní data
// ============================================================

const GAME_DATA = {

  // --- PŘEDMĚTY ---
  items: {
    smetak: { id: 'smetak', name: 'Smeták-kytara', icon: '🧹', locationId: 'sulcovi', sleepReduction: 25, desc: 'Brian May + Jimi Hendrix = rockový gén!' },
    plzen: { id: 'plzen', name: 'Půllitr tankové Plzníňky', icon: '🍺', locationId: 'oocka', sleepReduction: 35, desc: 'Čerstvě natočená, vychlazená.' },
    svecena: { id: 'svecena', name: 'Svěcená voda', icon: '🥛', locationId: 'kostel', sleepReduction: 30, desc: 'Požehnaná voda. Zdvojnásobí sílu jako první! (×2)' },
    kybl: { id: 'kybl', name: 'Kýbl ledové vody', icon: '🫗', locationId: 'vackovi', sleepReduction: 40, desc: 'Nic neprobere líp než ledová voda.' },
    nandralon: { id: 'nandralon', name: 'Pixla Nandralonu', icon: '💊', locationId: 'posilovna', sleepReduction: 50, desc: 'Koňská síla zapálí i stromky!' },
    katalog: { id: 'katalog', name: 'Katalog Volva V70 Diesel', icon: '🚗', locationId: 'krecovi', sleepReduction: 60, desc: 'Tichá síla při 2200 RPM.' },
    helma: { id: 'helma', name: 'Aerodynamická helma', icon: '🪖', locationId: 'vetraci', sleepReduction: 65, desc: 'S hrotem. Au! Ale vždycky pomůže.' },
    panak: { id: 'panak', name: 'Panák zelené s Redbullem', icon: '🍸', locationId: 'kozlovna', sleepReduction: 70, desc: 'Zelený Hulk v součinnosti!' },
    koliucky: { id: 'koliucky', name: 'Kolíčky na bradavky', icon: '🧷', locationId: 'franci', sleepReduction: 78, desc: 'Bolest jako učitel bdělosti.' },
    paratka: { id: 'paratka', name: 'Párátka do očí (patent dr. Fíši)', icon: '🥢', locationId: 'fisa', sleepReduction: 85, desc: 'Vidí komáry v 50 metrech! Absolutní maximum.' },
  },

  // --- KOMBA ---
  combos: [
    { items: ['paratka', 'smetak'], bonus: 18, label: 'Párátka + Smeták', desc: '🔥 MAXIMUM VISION! Oči dokořán, hraj Hendrixi!' },
    { items: ['koliucky', 'kybl'], bonus: 16, label: 'Kolíčky + Kýbl', desc: '🔥 POLÁRNÍ ŠMRC! Bolest + chlad = superbdělost!' },
    { items: ['katalog', 'helma'], bonus: 10, label: 'Katalog + Helma', desc: 'Cítím uvnitř mozku, jak si Volvo tiše ševelí...' },
    { items: ['nandralon', 'panak'], bonus: 22, label: 'Nandralon + Panák', desc: '🔥 ZELENÝ HULK! Koňská síla na steroidech!' },
    { items: ['paratka', 'kybl'], bonus: 14, label: 'Párátka + Kýbl', desc: 'OSTRÉ ZMRZNUTÍ! Oči vidí každou sněhovou vločku!' },
    { items: ['koliucky', 'helma'], bonus: 12, label: 'Kolíčky + Helma', desc: 'Double PAIN GAMING! Bolest je tvůj nejlepší druh!' },
    { items: ['svecena', 'nandralon'], bonus: 13, label: 'Svěcená + Nandralon', desc: 'POSVÁTNÁ KOŇSKÁ SÍLA! Zázrak v svalech!' },
    { items: ['katalog', 'plzen'], bonus: 11, label: 'Katalog + Plzeň', desc: 'Doslova intelektuální pití! Perfektní!' },
    { items: ['smetak', 'panak'], bonus: 9, label: 'Smeták + Panák', desc: 'ROCK & ROLL! Hudba + energie = BING!' },
  ],

  // --- ANTI-KOMBA (rušení) ---
  anticombos: [
    { after: 'kybl', cancels: 'smetak', desc: '💀 MOKRÝ SMETÁK = MRTVÁ HUDBA! Hendrix by brečel.' },
    { after: 'katalog', cancels: 'paratka', desc: '💀 ČTENÍ V 50 METRECH? Brain overload! Mozek vypnout!' },
    { after: 'paratka', cancels: 'katalog', desc: '💀 VIDÍM V70 PŘÍLIŠ JASNĚ! Přestanu věřit, že je to diesel.' },
    { after: 'helma', cancels: 'paratka', desc: '💀 HELMA DRŽÍ PÁRÁTKA V HLAVĚ! Mozková jiskra = SHORT CIRCUIT!' },
    { after: 'paratka', cancels: 'helma', desc: '💀 PÁRÁTKA VIDÍ HELMU JAKO HROZBU! Oči se zavřou - dark mode!' },
    { after: 'plzen', cancels: 'svecena', desc: '💀 SVATÁ VODA + PIVO = NEJHORŠÍ KOKTEJL! Boží vůle: Honza usne.' },
    { after: 'panak', cancels: 'svecena', desc: '💀 ZELENÁ NA SVATOU? Ďábel se smál. Svěcenost do pece!' },
    { after: 'smetak', cancels: 'koliucky', desc: '💀 HUDBA + BOLEST = DEATH METAL V DUŠEVNÍ AGÓNII! Cancel all!' },
    { after: 'koliucky', cancels: 'smetak', desc: '💀 BOLEST ZABILA HUDBU! Párátka se chvějí, smeták mrtev.' },
    { after: 'panak', cancels: 'plzen', desc: '💀 ZELENÁ + ZLATÁ = NEON OPILOSTI! Vidím trojitě, chci spát.' },
    { after: 'plzen', cancels: 'panak', desc: '💀 PIVO + PANÁK = OPILÝ ZELENÝ DUCH! Kůň padá, Honza padá.' },
    { after: 'nandralon', cancels: 'plzen', desc: '💀 KOŇSKÁ SÍLA + PIVO = OPILÝ KŮŇ! Kůň padá do kómatu.' },
    { after: 'plzen', cancels: 'nandralon', desc: '💀 PIVO SNÍŽÍ KOŇSKOU SÍLU! Raději spí, než přepadá stromky.' },
    { after: 'nandralon', cancels: 'panak', desc: '💀 PŘÍLIŠ SILNÁ! Nandralon + Panák = EXPLOSION! Honza exploduje.' },
    { after: 'panak', cancels: 'nandralon', desc: '💀 PANÁK ROZLOŽÍ KOŇSKOU SÍLU! Svalům hrozí rozpad. Spánek je záchrana.' },
  ],

  // --- SPECIÁLNÍ: Svěcená voda jako první ---
  svecenaFirstBonus: true, // ×2 pokud je první použitý předmět

  // --- LOKACE ---
  locations: [
    {
      id: 'sulcovi',
      num: 1,
      name: 'Dům Šulců',
      emoji: '🏠',
      mapX: 30, mapY: 52,
      characters: ['Markéta', 'Anička', 'Emma', 'Garp'],
      item: 'smetak',
      color: '#e8734a',
      bgColor: '#fff3ee',
      scenes: [
        { type: 'image', src: '01_Sulc_01.png' },
        { type: 'dialog' },
        { type: 'image', src: '01_Sulc_02.png' },
        { type: 'image', src: '01_Sulc_03.png' },
        { type: 'minigame' },
        { type: 'image', src: '01_Sulc_04.png' },
        { type: 'item' },
      ],
      dialog: {
        speaker: 'Markéta',
        speakerEmoji: '👩',
        text: 'Jé, ahoj! To jdeš zachránit situaci?',
        options: [
          { text: 'A) Markéto, nech ho spát. Třeba je to power nap à la Elon Musk – za 20 minut vstane a pošle auto na Mars.', correct: false, reaction: 'Markéta kroutí hlavou: „To určitě ne! Honza musí grilovat čuníka!"' },
          { text: 'B) Markéto, co na něj fakt platí? Co to máš za ten smeták? To je Gandalfova hůl?', correct: true },
          { text: 'C) Co zapojit psa? Garp je loveckej, ať ho vystopuje a probudí!', correct: false, reaction: 'Garp radostně zavrtí ocasem, ale Markéta kroutí hlavou: „Garp je líný jako Honza!"' },
        ],
        successText: 'Markétě se rozzáří oči: „Anička jednou zjistila, že když dáš Honzovi smeták, zahraje neviditelné sólo jako Brian May!"',
        successSub: 'Ale pozor – kdybys ho polil vodou, smeták ztratí kouzlo!',
      },
      minigame: 'pexeso',
    },
    {
      id: 'vackovi',
      num: 2,
      name: 'Dům Vacků',
      emoji: '🏊',
      mapX: 36, mapY: 35,
      characters: ['Váca', 'Alena', 'Emča', 'Honza'],
      item: 'kybl',
      color: '#4a90d9',
      bgColor: '#eef4ff',
      scenes: [
        { type: 'image', src: '02_Vaca_01.png' },
        { type: 'dialog' },
        { type: 'minigame' },
        { type: 'image', src: '02_Vaca_02.png' },
        { type: 'image', src: '02_Vaca_03.png' },
        { type: 'item' },
      ],
      dialog: {
        speaker: 'Váca',
        speakerEmoji: '🔧',
        text: 'Nazdar! Honza už zase klimbá, že jo? Já ti řeknu co funguje – ICE BATH!!',
        options: [
          { text: 'A) Váco, nemáš raději studený pivko? To je taky tekutina...', correct: false, reaction: 'Váca se chechtá: „Pivo? To ho akorát ještě víc uspí, kamaráde!"' },
          { text: 'B) Kýbl ledový vody? To je jako Ice Bucket Challenge, ale s terapeutickým účinkem. Beru!', correct: true },
          { text: 'C) Kdepak studená voda... Na Honzu platí jedině četba výročních zpráv EBM zpětně od roku 2018.', correct: false, reaction: 'Váca: „Ha! To by fungovalo, ale kde ty zprávy sehnat..."' },
        ],
        successText: 'Váca jásá: „Tady to máš, lepší než živá voda – Honzu to vytočí minimálně na 1000 watů!"',
        successSub: 'Ale dávej si bacha – hlavně na něj nelij vodu před nebo po kytarovém vystoupení...',
      },
      minigame: 'anagramy',
    },
    {
      id: 'krecovi',
      num: 3,
      name: 'Dům Krečů',
      emoji: '📰',
      mapX: 38, mapY: 28,
      characters: ['Lubo', 'Krista', 'Thea', 'Elda'],
      item: 'katalog',
      color: '#2ecc71',
      bgColor: '#efffef',
      scenes: [
        { type: 'image', src: '03_Krec_01.png' },
        { type: 'dialog' },
        { type: 'minigame' },
        { type: 'image', src: '03_Krec_02.png' },
        { type: 'image', src: '03_Krec_03.png' },
        { type: 'item' },
      ],
      dialog: {
        speaker: 'Lubo',
        speakerEmoji: '🎙️',
        text: 'Šulcík usíná? To je mi novinka jak sell the news, buy the rumor. Ale vím co pomůže...!',
        options: [
          { text: 'A) Kafe a red bull. To je dvojitý espresso do žil.', correct: false, reaction: 'Lubo mávne rukou: „Kafe? To je pro slabochy. Honza kafe nesnáší!"' },
          { text: 'B) Něco o autech! Volvo, nejlépe s motorem z traktoru – to je jeho fetiš. Skvělý!', correct: true },
          { text: 'C) Dej mu přehled změn Stavebního zákona za poslední kvartál, to ho vždycky spolehlivě probudí...', correct: false, reaction: 'Lubo: „Hm... to by možná fungovalo, ale nemám aktuální znění."' },
        ],
        successText: 'Lubo s úsměvem podává lesklý katalog: „Jeho fetiš: starý diesel a traktorový zvuk. Jakmile to uvidí, bude šťastnej."',
        successSub: 'Jestli má párátka v očích, tak slzí a nečte. Spíš se vztekne. Takže nejdřív katalog, až pak mučení.',
      },
      minigame: 'sudoku',
    },
    {
      id: 'vetraci',
      num: 4,
      name: 'Dům Větráků',
      emoji: '📺',
      mapX: 43, mapY: 58,
      characters: ['Větrák', 'Katka', 'Adéla', 'Adam'],
      item: 'helma',
      color: '#9b59b6',
      bgColor: '#f5eeff',
      scenes: [
        { type: 'image', src: '04_Vetrak_01.png' },
        { type: 'dialog' },
        { type: 'image', src: '04_Vetrak_02.png' },
        { type: 'minigame' },
        { type: 'image', src: '04_Vetrak_03.png' },
        { type: 'image', src: '04_Vetrak_04.png' },
        { type: 'item' },
      ],
      dialog: {
        speaker: 'Větrák',
        speakerEmoji: '🍺',
        text: 'Šulcík potřebuje přítlak! Vyrobil jsem mu aerodynamickou helmu proti usnutí – inspirovaná časovkou z Tour.',
        options: [
          { text: 'A) To je ono: vypadá to jako kříženec Dartha Vadera s toustovačem, ale určitě nám to přidá vteřiny... Beru!!!', correct: true },
          { text: 'B) Raději mu pustím projev Ursuly von der Leyen o Green Dealu – to ho sice uspí, ale aspoň bude poučeně spát.', correct: false, reaction: 'Větrák: „Green Deal?! Tohle je grilovačka, ne europarlament!"' },
          { text: 'C) Nemáš místo toho polštářek s vůní levandule a ASMR zvuky tropického deště?', correct: false, reaction: 'Větrák se rozřehtal: „Levanduláč?! Ty jsi tu správnou hrou přišel?!"' },
        ],
        successText: 'Větrák září: „Přesně! Skloníš hlavu → bodec → probudíš se. Permanentní alarm, čirej life-hack."',
        successSub: 'Z právního hlediska ti měla říct, že tohle je hranice mezi asistencí a ublížením na zdraví... Tak jen ať si už nic neaplikuje do očí.',
      },
      minigame: 'vlastovka',
    },
    {
      id: 'oocka',
      num: 5,
      name: 'Dům Óóček',
      emoji: '🔥',
      mapX: 17, mapY: 48,
      characters: ['Janek', 'Petra', 'Kubík', 'Nina'],
      item: 'plzen',
      color: '#f39c12',
      bgColor: '#fffbee',
      scenes: [
        { type: 'image', src: 'Pictures/05_Oo_01.png' },
        { type: 'dialog' },
        { type: 'image', src: 'Pictures/05_Oo_02.png' },
        { type: 'minigame' },
        { type: 'image', src: 'Pictures/05_Oo_03.png' },
        { type: 'image', src: 'Pictures/05_Oo_04.png' },
        { type: 'item' },
      ],
      dialog: {
        speaker: 'Janek',
        speakerEmoji: '🍻',
        text: 'Nazdar! Honza už zase spí? To chce Plzníňku! Tady máš čerstvě natočenou – to ho probere!',
        options: [
          { text: 'A) Alkohol? To je cesta do pekel, vždyť po dvou pivech spí jak nemluvně!', correct: false, reaction: 'Janek se usměje: „To je právě to – jedno pivo ho probere, dva ho usnou. Všechno je v dávce!"' },
          { text: 'B) Ty vole, Plzníňka! To je jako dát mu tekutou naději. Díky!', correct: true },
          { text: 'C) Nemáš radši kombuchu nebo cold brew? To je moderní probuzení.', correct: false, reaction: 'Janek se podrbe: „Kombucha? Na grilovačce? To bys musel jít na wellness resort, kamaráde."' },
        ],
        successText: 'Janek se chechtá: „Správně! Jedna Plzníňka a je to. Chladná, osvěžující, a Honza bude na nohách!"',
        successSub: 'Petra: „Ale bacha – kdyby ji dal s panákem ze Kozlovny, bude z toho jen unavenej alkáč. Tak jeden věc po druhé!"',
      },
      minigame: 'svetylka',
    },
    {
      id: 'franci',
      num: 6,
      name: 'Dům Franců',
      emoji: '⛳',
      mapX: 47, mapY: 55,
      characters: ['Jarda', 'Vlastička'],
      item: 'koliucky',
      color: '#27ae60',
      bgColor: '#edfff3',
      scenes: [
        { type: 'image', src: 'Pictures/06_Franc_01.png' },
        { type: 'image', src: 'Pictures/06_Franc_02.png' },
        { type: 'dialog' },
        { type: 'image', src: 'Pictures/06_Franc_03.png' },
        { type: 'minigame' },
        { type: 'image', src: 'Pictures/06_Franc_04.png' },
        { type: 'item' },
      ],
      dialog: {
        speaker: 'Jarda',
        speakerEmoji: '🏌️',
        text: 'Víš, co je na golfu nejdůležitější? Soustředění. A na Honzu platí tohle – přinesl jsem to pro jistotu. (tajemně ukazuje dřevěné kolíčky se srdíčkem)',
        options: [
          { text: 'A) To je... kolíček na prádlo? Chceš, aby si pověsil košili?', correct: false, reaction: 'Jarda vzdychne: „To by byla selhání vymýšlení. Zamysli se!"' },
          { text: 'B) Na co to je? Na bradavky?! To je geniálně zvrácený!', correct: true },
          { text: 'C) Ty jsi úchyl, ale přesně takového kamaráda Honza potřebuje. Beru to!', correct: true },
        ],
        successText: 'Jarda se rozesměje: „Správně! Když to dáš dohromady s ledovou vodou, bude to jako na mistrovství světa v křiku!"',
        successSub: 'Vlastička: „Jen mu to neaplikuj v okamžiku, kdy bude vybrnkávat kytarové sólíčko... to by si ty kolíčky tak neužil."',
      },
      minigame: 'sibenice',
    },
    {
      id: 'fisa',
      num: 7,
      name: 'Dům Dr. Fíši',
      emoji: '🩺',
      mapX: 46, mapY: 53,
      characters: ['Dr. Fíša'],
      item: 'paratka',
      color: '#e74c3c',
      bgColor: '#fff0ef',
      scenes: [
        { type: 'image', src: 'Pictures/07_Fisa_01.png' },
        { type: 'image', src: 'Pictures/07_Fisa_02.png' },
        { type: 'dialog' },
        { type: 'minigame' },
        { type: 'image', src: 'Pictures/07_Fisa_03.png' },
        { type: 'item' },
      ],
      dialog: {
        speaker: 'Dr. Fíša',
        speakerEmoji: '👨‍⚕️',
        text: 'Kolego, spánek je přežitek! Tady mám svůj patent – profesionální držáky očí. Zaveď je Honzovi, až bude usínat. Úspěch zaručen! A ano – jsou to párátka.',
        options: [
          { text: 'A) To je barbarství! Copak jsi doktor Mengele?', correct: false, reaction: 'Fíša se uraženě nafoukne: „Mengele?! Já jsem vědecký genij, ne fašista!"' },
          { text: 'B) Jestli to funguje, tak ať je to klidně z ježkových bodlin. Beru! Lékařská věda nezná hranic.', correct: true },
          { text: 'C) Nechci mu vypíchnout oko, nemáš radši modrý sklípek na spaní?', correct: false, reaction: 'Fíša: „Sklípek?! To není řešení, to je jen procrastinace!"' },
        ],
        successText: 'Fíša je nadšený: „Správná volba! Vědecký přístup! Když mu potom dáš do ruky hudební nástroj, bude mít oči dokořán a myslet si, že je superstar!"',
        successSub: '"Ale ať si nebere nic na hlavu – mohlo by mu to tlačit na spánky a párátka by vypadla!"',
      },
      minigame: 'kviz',
    },
    {
      id: 'kozlovna',
      num: 8,
      name: 'Kozlovna (hospoda)',
      emoji: '🍺',
      mapX: 68, mapY: 67,
      characters: ['Výčepní'],
      item: 'panak',
      color: '#c0392b',
      bgColor: '#fff5f5',
      scenes: [
        { type: 'image', src: 'Pictures/08_Kozlovna_01.png' },
        { type: 'image', src: 'Pictures/08_Kozlovna_02.png' },
        { type: 'dialog' },
        { type: 'minigame' },
        { type: 'image', src: 'Pictures/08_Kozlovna_03.png' },
        { type: 'image', src: 'Pictures/08_Kozlovna_04.png' },
        { type: 'item' },
      ],
      dialog: {
        speaker: 'Výčepní',
        speakerEmoji: '🍻',
        text: 'Fun fact: víte, že směs Red Bullu a zelené peprmintky dokáže nakopnout i mrtvého koně? Chceš to zkusit na Honzu?',
        options: [
          { text: 'A) Dej mi to! Ať je to silný jako Trumpovo ego, ale s lepšími následky!', correct: true },
          { text: 'B) Nechci, aby mu explodovalo srdce. Radši klasický pivo.', correct: false, reaction: 'Výčepní pokrčí rameny: „Pivo? Na tuhle akci? Neboj se riskovat!"' },
          { text: 'C) Máš něco veganského? Třeba matcha latte?', correct: false, reaction: 'Výčepní se smeje: „Matcha? Tady? Ty ses spletl hospodu!"' },
        ],
        successText: 'Výčepní s ďábelským úsměvem mixuje: „Správně! Tady to máš! A víš co? Zkombinuj to s tím z posilovny – bude z něj učiněnej zelenej Hulk!"',
        successSub: '"Ale dej si bacha – kdybys to zkombinoval s pivem, bude z toho jenom unavenej opilec."',
      },
      minigame: 'natocpivo',
    },
    {
      id: 'posilovna',
      num: 9,
      name: 'Posilovna 21',
      emoji: '💪',
      mapX: 56, mapY: 48,
      characters: ['Trenérka'],
      item: 'nandralon',
      color: '#e67e22',
      bgColor: '#fff8ee',
      scenes: [
        { type: 'image', src: 'Pictures/09_Fitko_01.png' },
        { type: 'image', src: 'Pictures/09_Fitko_02.png' },
        { type: 'dialog' },
        { type: 'minigame' },
        { type: 'image', src: 'Pictures/09_Fitko_03.png' },
        { type: 'image', src: 'Pictures/09_Fitko_04.png' },
        { type: 'item' },
      ],
      dialog: {
        speaker: 'Trenérka',
        speakerEmoji: '🏋️‍♀️',
        text: 'Čau! Neříkej mi, že Honzovi zase klesl tep pod 40? To chce něco na prokrvení! Mám exkluzivní pixličku Nandralónku – je to sice pro koně, ale funguje to i na lidi!',
        options: [
          { text: 'A) To je doping! Chci čistý sport!', correct: false, reaction: 'Trenérka mrkne: „Doping je jen pro závody. Tohle je... terapeutická pomůcka."' },
          { text: 'B) Radší si s ním dám 500 angličáků, to ho taky probudí.', correct: false, reaction: 'Trenérka: „500 angličáků ho zabije, ne probudí. Buď rozumný!"' },
          { text: 'C) Super, zůstane vzhůru a navíc mu narostou bicepsy. Beru!', correct: true },
        ],
        successText: 'Trenérka mrkne: „Přesně! A jestli to zapiješ tím zeleným bejčím ionťákem, bude z něj nezastavitelný stroj!"',
        successSub: '"Ale jestli si předtím dal pivo, nebude to tak efektivní – alkohol ředí účinek."',
      },
      minigame: 'anglicaky',
    },
    {
      id: 'kostel',
      num: 10,
      name: 'Kostel',
      emoji: '⛪',
      mapX: 72, mapY: 46,
      characters: ['Kněz', 'Jan Hus'],
      item: 'svecena',
      color: '#8e44ad',
      bgColor: '#f9f0ff',
      scenes: [
        { type: 'image', src: 'Pictures/10_Kostel_01.png' },
        { type: 'image', src: 'Pictures/10_Kostel_02.png' },
        { type: 'dialog' },
        { type: 'minigame' },
        { type: 'image', src: 'Pictures/10_Kostel_03.png' },
        { type: 'image', src: 'Pictures/10_Kostel_04.png' },
        { type: 'item' },
      ],
      dialog: {
        speaker: 'Kněz',
        speakerEmoji: '✝️',
        text: 'Synu, spánek je hřích! Zde je svěcená voda proti démonům ospalosti. Chceš ji?',
        options: [
          { text: 'A) Amen, bratře. Svatá voda do boje proti únavě a padajícím očím!', correct: true },
          { text: 'B) Nevěřím v zázraky, radši mu dám kávu s máslem.', correct: false, reaction: 'Kněz se zachvěje: „Nevěřící! Kafe je výmysl ďábla! Nebo tedy... Arabů."' },
          { text: 'C) Nepotřebuju exorcismus, díky, jen ať spí spánkem zaslouženým.', correct: false, reaction: 'Kněz: „Vymítání? To bychom potřebovali celý den. Na toto stačí jen voda!"' },
        ],
        successText: 'Kněz pokropí flakónek: „Požehnejž tobě i téhle vodě. Pamatuj – pokud ji použiješ jako první věc večera, její síla se zdvojnásobí!"',
        successSub: 'Jan Hus z obrazu: „Ale po pivu a zelený, příteli, ta svatost odchází jako pára nad hrncem. Žehu zdar!"',
      },
      minigame: 'rozdily',
    },
  ],

  // --- AVATAR TYPY ---
  avatars: [
    { id: 'f1', gender: 'f', color: '#e74c3c', hair: 'long', label: 'Červenovláska' },
    { id: 'f2', gender: 'f', color: '#9b59b6', hair: 'curly', label: 'Fialová dáma' },
    { id: 'f3', gender: 'f', color: '#f39c12', hair: 'bun', label: 'Blondýnka' },
    { id: 'm1', gender: 'm', color: '#2ecc71', hair: 'short', label: 'Zelený borec' },
    { id: 'm2', gender: 'm', color: '#3498db', hair: 'medium', label: 'Modrý typ' },
    { id: 'm3', gender: 'm', color: '#e67e22', hair: 'bald', label: 'Plešoun' },
  ],

  // --- SLOVÍČKA PRO ANAGRAMY (lokace Vacků) ---
  anagramWords: [
    { word: 'VOLVO',      hint: 'Honzův oblíbený vůz' },
    { word: 'PUMPIČKA',   hint: 'Na kolo' },
    { word: 'PROTEIN',    hint: 'V šejkru po tréninku' },
    { word: 'KAPITÁN',    hint: 'Vůdce týmu' },
    { word: 'ŠLAPKA',     hint: 'Cyklistický pedál' },
    { word: 'TRENÉR',     hint: 'Ten, kdo tě trénuje' },
    { word: 'KLADNO',     hint: 'Naše město' },
    { word: 'RACEK',      hint: 'Pták nad bazénem' },
    { word: 'MARINGOTKA', hint: 'Pojízdný příbytek' },
    { word: 'KOŠTĚ',      hint: 'Čím zamete Markéta' },
    { word: 'BIANCHI',    hint: 'Italské kolo' },
    { word: 'CYKLISTIKA', hint: 'Vácův sport' },
    { word: 'PROJEKT',    hint: 'Co Váca řídí' },
    { word: 'OCHLAZOVNA', hint: 'Po sauně' },
    { word: 'PIVO',       hint: 'Vácovo oblíbené' },
    { word: 'BAZÉN',      hint: 'Vácova zahrada' },
  ],

  // --- SLOVA PRO ŠIBENICI (lokace Franců) ---
  hangmanWords: [
    { word: 'BIRDIE', hint: 'Když hrajete jako pán a máte o ránu méně.' },
    { word: 'KORMIDLO', hint: 'Volant, kterým se točí, když to hodně fouká.' },
    { word: 'PLACHTA', hint: 'Velké prostěradlo, do kterého musí fouknout.' },
    { word: 'PALUBA', hint: 'Terasa, která se pod vámi pořád hýbe.' },
    { word: 'KOTVA', hint: 'Těžké železo, co drží loď na vodítku.' },
    { word: 'KAPITÁN', hint: 'Ten, co má čepici a vždycky pravdu.' },
    { word: 'VESTA', hint: 'Oranžový módní doplněk pro neplavce.' },
    { word: 'LAVINA', hint: 'Sníh, který se rozhodl jet dolů zkratkou.' },
    { word: 'LANOVKA', hint: 'Pohodlný výtah pro líné turisty.' },
    { word: 'MAČKY', hint: 'Železná kusadla na boty proti uklouznutí.' },
    { word: 'PLESO', hint: 'Horské zrcadlo, ve kterém se nekoupe.' },
    { word: 'SKIALPY', hint: 'Lyže, se kterými se do kopce nefuní marně.' },
    { word: 'VĚŽÁKY', hint: 'Panelové dominanty, které vidíte už z dálky.' },
    { word: 'POLDOVKA', hint: 'Legenda z oceli, co dala městu jméno.' },
    { word: 'RYTÍŘI', hint: 'Hokejoví bojovníci s kladenským srdcem.' },
    { word: 'HALDY', hint: 'Umělé kopce, co zbyly po těžké práci.' },
    { word: 'SLETIŠTĚ', hint: 'Místo, kde Kladno sportuje a nabírá dech.' },
  ],

  // --- KVÍZ OTÁZKY (lokace Dr. Fíši) ---
  quizQuestions: [
    {
      q: 'Jak dlouho trval nejdelší tenisový zápas v historii?',
      options: ['11 hodin a 5 minut', 'Dokud oba hráči neusnuli vestoje', 'Tak dlouho, že se vítěz musel po zápase znovu oholit'],
      correct: 0,
      explanation: 'Isner vs Anderson v Wimbledonu 2019 – rekord v profesionálním tenisu!',
    },
    {
      q: 'Jaký sport se oficiálně hrál na povrchu Měsíce?',
      options: ['Šachy s kameny', 'Golf', 'Přetahování o kyslíkovou bombu'],
      correct: 1,
      explanation: 'Astronaut Alan Shepard zahrál golfový výstřel na Měsíci v roce 1971!',
    },
    {
      q: 'Co je to tzv. Coffee Badging?',
      options: ['Umění udělat si v práci 15 káv za hodinu', 'Přijít do kanclu jen na kafe, aby vás viděli, a pak jít domů', 'Sbírání razítek za každého kolegu, kterého u kávovaru pomluvíte'],
      correct: 1,
      explanation: 'Moderní fenomén – pracovník se ukáže v kanclu a pak pracuje z domu!',
    },
    {
      q: 'Co se stane v Japonsku, když zaměstnanec v práci usne?',
      options: ['Je to bráno jako důkaz totálního vyčerpání z práce a má respekt', 'Kolegové mu na čelo nakreslí logo konkurence', 'Musí za trest týden vařit rýži v kantýně'],
      correct: 0,
      explanation: 'V Japonsku se to nazývá inemuri – znamená vysokou pracovní morálku.',
    },
    {
      q: 'Jaká byla původní barva loga Microsoftu?',
      options: ['Barva čerstvě vytěženého uhlí', 'Agresivní neonová zelená', 'Disko barvy se stylovým názvem Blibbet'],
      correct: 2,
      explanation: 'Původní logo bylo křiklavě zelené – dnes známe modrého Microsoftu.',
    },
    {
      q: 'Proč se lenochodi občas omylem zabijí?',
      options: ['Spletou si vlastní ruku s větví a spadnou', 'Zapomenou se nadechnout, jak jsou pomalí', 'Předávkují se listy a dostanou nekontrolovaný záchvat smíchu'],
      correct: 0,
      explanation: 'Jejich reflexy jsou tak pomalé, že si spletou vlastní ruku s větví!',
    },
    {
      q: 'Co dělají vombati se svým trusem, aby se jim nerozkutálel?',
      options: ['Olizují ho do tvaru pyramidy', 'Kadí ho ve tvaru kostek', 'Schovávají ho do kapes u sousedů'],
      correct: 1,
      explanation: 'Vombati produkují kubické trus – používají ho jako značku teritoria!',
    },
    {
      q: 'Co dělal Isaac Newton, aby zjistil, jak funguje lidské oko?',
      options: ['Píchal si pletací jehlici pod oční bulvu', 'Sledoval zatmění slunce, dokud neoslepl na levé oko', 'Snažil se zhypnotizovat jablko, aby nespadlo'],
      correct: 0,
      explanation: 'Newton si opravdu píchal jehlicí pod oko – pro vědu! (Nekopírovat!)',
    },
    {
      q: 'Jaký kuriózní fetiš měl spisovatel Victor Hugo?',
      options: ['Psal nahý a šaty schoval sluhovi, aby nemohl odejít ven', 'Jedl každý den k snídani dvě kila hrušek', 'Sbíral knoflíky od svých milenek do velké sklenice od okurek'],
      correct: 0,
      explanation: 'Hugo měl bizarní pracovní zvyky – psaní v minimálním oděvu byla jeho norma.',
    },
    {
      q: 'Který slavný vojevůdce byl napaden a zahnán na útěk tisíci králíky?',
      options: ['Napoleon Bonaparte', 'Julius Caesar', 'Attila Bič Boží'],
      correct: 0,
      explanation: 'Napoleon se během lovu v Egyptě setkal s králičím útokem!',
    },
    {
      q: 'Jak dopadl Charlie Chaplin v soutěži o svého nejlepšího dvojníka?',
      options: ['Vyhrál ji se zavázanýma očima', 'Skončil až na 20. místě', 'Byl diskvalifikován, protože vypadal málo jako Chaplin'],
      correct: 1,
      explanation: 'Ironické – Chaplin v soutěži o Chaplina neuspěl!',
    },
    {
      q: 'Co původně znamenalo písmeno i v názvu iMac (a později iPhone)?',
      options: ['i jako Já (Narcis mode)', 'Internet, individualita, instrukce, informace, inspirace', 'Iritující, protože na to nikdo neměl peníze'],
      correct: 1,
      explanation: 'Steve Jobs měl pět slov – Internet, Individual, Instruct, Inform, Inspire!',
    },
    {
      q: 'Kdo byl na úplně prvním logu Applu, než ho nahradilo nakousnuté jablko?',
      options: ['Isaac Newton sedící pod stromem', 'Červík v brýlích, který čte knihu', 'Sněhurka, která se právě otrávila'],
      correct: 0,
      explanation: 'Isaac Newton pod stromem – proto i nakousnuté jablko jako reference!',
    },
    {
      q: 'Jaký speciální režim můžete spustit v Tesle, abyste pobavili kolemjdoucí?',
      options: ['Režim Prdění (Emissions Testing Mode), který vydává zvuky z reproduktorů', 'Režim Neviditelnost, který vypne všechna světla a auto se tváří jako tma', 'Režim Diskotéka, kdy auto začne samo od sebe otvírat a zavírat dveře'],
      correct: 0,
      explanation: 'Tesla má opravdu Emissions Testing Mode – auto vydává vtipné zvuky!',
    },
    {
      q: 'Proč se Tesla Model Y a další modely jmenují zrovna takto (S, X, 3)?',
      options: ['Protože Musk chtěl, aby dohromady tvořily slovo S3XY', 'Jsou to náhodná písmena, která mu zbyla v polévce', 'Je to kód k trezoru, kde schovává plány na kolonizaci Marsu'],
      correct: 0,
      explanation: 'S, 3, X, Y dohromady dávají S3XY – Musk má smysl pro humor!',
    },
    {
      q: 'Jak se jmenují lodě, které v oceánu chytají dopadající části raket?',
      options: ['Samozřejmě, že tě stále miluju a Jen si přečti instrukce', 'Velká ruka a Chytej, vole', 'Titanic 2 a Nepotopitelná Naději'],
      correct: 0,
      explanation: 'Lodě SpaceX se jmenují po I Still Love You z kulturních referencí!',
    },
    {
      q: 'Jaký sport se oficiálně hrál na povrchu Měsíce?',
      options: ['Šachy s kameny', 'Golf', 'Přetahování o kyslíkovou bombu'],
      correct: 1,
      explanation: 'Astronaut Alan Shepard zahrál golfový výstřel na Měsíci v roce 1971!',
    },
    {
      q: 'Co je to tzv. „Coffee Badging"?',
      options: ['Umění udělat si v práci 15 káv za hodinu', 'Přijít do kanclu jen na kafe, aby vás viděli, a pak jít domů', 'Sbírání razítek za každého kolegu, kterého u kávovaru pomluvíte'],
      correct: 1,
    },
    {
      q: 'Co se stane v Japonsku, když zaměstnanec v práci usne?',
      options: ['Je to bráno jako důkaz totálního vyčerpání z práce a má respekt', 'Kolegové mu na čelo nakreslí logo konkurence', 'Musí za trest týden vařit rýži v kantýně'],
      correct: 0,
    },
    {
      q: 'Jaká byla původní barva loga Microsoftu?',
      options: ['Barva čerstvě vytěženého uhlí', 'Agresivní neonová zelená', 'Disko barvy se stylovým názvem „Blibbet"'],
      correct: 2,
    },
    {
      q: 'Proč se lenochodi občas omylem zabijí?',
      options: ['Spletou si vlastní ruku s větví a spadnou', 'Zapomenou se nadechnout, jak jsou pomalí', 'Předávkují se listy a dostanou nekontrolovaný záchvat smíchu'],
      correct: 0,
    },
    {
      q: 'Co dělají vombati se svým trusem, aby se jim nerozkutálel?',
      options: ['Olizují ho do tvaru pyramidy', 'Kadí ho ve tvaru kostek', 'Schovávají ho do kapes u sousedů'],
      correct: 1,
    },
    {
      q: 'Co dělal Isaac Newton, aby zjistil, jak funguje lidské oko?',
      options: ['Píchal si pletací jehlici pod oční bulvu', 'Sledoval zatmění slunce, dokud neoslepl na levé oko', 'Snažil se zhypnotizovat jablko, aby nespadlo'],
      correct: 0,
    },
    {
      q: 'Jaký kuriózní fetiš měl spisovatel Victor Hugo?',
      options: ['Psal nahý a šaty schoval sluhovi, aby nemohl odejít ven', 'Jedl každý den k snídani dvě kila hrušek', 'Sbíral knoflíky od svých milenek do velké sklenice od okurek'],
      correct: 0,
    },
    {
      q: 'Který slavný vojevůdce byl napaden a zahnán na útěk tisíci králíky?',
      options: ['Napoleon Bonaparte', 'Julius Caesar', 'Attila Bič Boží'],
      correct: 0,
    },
    {
      q: 'Jak dopadl Charlie Chaplin v soutěži o svého nejlepšího dvojníka?',
      options: ['Vyhrál ji se zavázanýma očima', 'Skončil až na 20. místě', 'Byl diskvalifikován, protože vypadal „málo jako Chaplin"'],
      correct: 1,
    },
    {
      q: 'Co původně znamenalo písmeno „i" v názvu iMac (a později iPhone)?',
      options: ['„I" jako „Já" (Narcis mode)', 'Internet, individualita, instrukce, informace, inspirace', '„Iritující", protože na to nikdo neměl peníze'],
      correct: 1,
    },
    {
      q: 'Kdo byl na úplně prvním logu Applu, než ho nahradilo nakousnuté jablko?',
      options: ['Isaac Newton sedící pod stromem', 'Červík v brýlích, který čte knihu', 'Sněhurka, která se právě otrávila'],
      correct: 0,
    },
    {
      q: 'Jaký speciální režim můžete spustit v Tesle, abyste „pobavili" kolemjdoucí?',
      options: ['Režim „Prdění" (Emissions Testing Mode), který vydává zvuky z reproduktorů', 'Režim „Neviditelnost", který vypne všechna světla a auto se tváří jako tma', 'Režim „Diskotéka", kdy auto začne samo od sebe otvírat a zavírat dveře'],
      correct: 0,
    },
    {
      q: 'Proč se Tesla Model Y a další modely jmenují zrovna takto (S, X, 3)?',
      options: ['Protože Musk chtěl, aby dohromady tvořily slovo „S3XY"', 'Jsou to náhodná písmena, která mu zbyla v polévce', 'Je to kód k trezoru, kde schovává plány na kolonizaci Marsu'],
      correct: 0,
    },
    {
      q: 'Jak se jmenují lodě, které v oceánu chytají dopadající části raket?',
      options: ['„Samozřejmě, že tě stále miluju" a „Jen si přečti instrukce"', '„Velká ruka" a „Chytej, vole"', '„Titanic 2" a „Nepotopitelná Naděje"'],
      correct: 0,
    },
  ],
};

// Export pro použití v jiných souborech
window.GAME_DATA = GAME_DATA;
